Inta v1
alekko/fotoaparats pull request #11
Opened 2020-10-21 13:54 UTC by intagrabe

Izveidoju jaunu zaru un ceru, ka beidzot viss izdevās

2020-10-27 19:30 UTC, alekko requested changes
Kopā ar kolēģi veiciet, lūdzu, labojumus kodā.

Klases rakstām angliski.
Lapas saturs latviski.
Cenšamies izmantot bootstrap.
Ddaudz lieka css mums ir. Ja tiešām vajag - tad atstājam.
Attēlus pārvietojam uz static/images

Jāsakārto indentācija, daudz lieku enteru. Bet ir jau labāk.

2020-10-27 19:30 UTC, alekko commented on images/stradnieks.svg
> +<path d="M250.736 32.4766C223.421 32.4766 197.225 47.3525 177.911 73.8317C158.597 100.311 147.746 136.225 147.745 173.672C147.745 192.214 150.409 210.575 155.585 227.706C160.761 244.837 168.347 260.4
Attēlus glabājam iekš static mapes.

2020-10-27 19:30 UTC, alekko commented on index.html
> +          <input class="parole1" type="password" placeholder="PAROLE">
Tas ir Jūsu kods?

Kaut kur redzētas klases parole un parole 1..

2020-10-27 19:30 UTC, alekko commented on index.html
> +          <button class="login" type="submit">LOGIN</button>
Latviskojam, tā pat kā koleģes kodā.

2020-10-27 19:30 UTC, alekko commented on static/css/index.css
> +  .login_form_container {
Man liekas, ka šis arī ir redzēts.

2020-11-04 11:03 UTC, intagrabe commented
Inta un Monta pievienoja js failus (users.js, rooms.js, tasks.js)

2020-11-09 16:33 UTC, alekko requested changes
Kas šis ir, JSON struktūras?

Jāpārsauc tad pull request apraksts + jāizdzēš visi nevajadzīgie/nesaistītie css html un attēli.

2020-11-09 19:54 UTC, intagrabe commented
Ceram, ka pareizi sapratām, ka visi citi faili ir jāizdzēš.

2020-11-23 22:29 UTC, merged