Monta
alekko/fotoaparats pull request #7
Opened 2020-10-20 14:43 UTC by mvanaga

Log-in un Pieteikuma skati 20.10.2020.

2020-10-27 19:24 UTC, alekko requested changes
Vajadzētu veikt labojumus:
- klases angliski
- viss saturs latviski
- padomāt, vai tiešām mums vajag tik daudz css?
- mēģinām iztikt ar bootstrap

2020-10-27 19:24 UTC, alekko commented on images/stradnieks.svg
> +<svg width="542" height="480" viewBox="0 0 542 480" fill="none" xmlns="http://www.w3.org/2000/svg">
Piedāvāju images mapi likt iekš static/images. Jo saturs nemainīsies, lai visi .css, .js un attēli atrodas iekš static.
Attiecīgi jāpārsauc būs visur tālāk kodā šis te ceļš līdz bildēm.

2020-10-27 19:24 UTC, alekko commented on index.html
> +    <div class="nosaukums">
Vai mums vajag šo un pārējās klases? Ar bootstrap kaut kas nesanāca?

Būtu forši, ja klases tad ieturētu vienā stilā, proti, angliski.

2020-10-27 19:24 UTC, alekko commented on index.html
> +          <button class="login" type="submit">LOGIN</button>
Pieslēgties? Domāju, ka varam visu redzamo daļu uzturēt latviski, savukārt kodā censties visu angliski.

2020-10-27 19:24 UTC, alekko commented on problem.html
> +        <img src="./images//stradnieks.svg" class="stradnieks" />
Pietiktu ar:
```
./images//stradnieks.svg
```

Bet pēc augstāk ierosinātās mapes pārvietošanas:
```
./static/images/stradnieks.svg
```

2020-10-27 19:24 UTC, alekko commented on static/css/index.css
> +  position: absolute;
Tā noteikti nedarām, nepārrakstām bootstrap stilus. Nu un absolute ļoti reti, kad vispār vajadzētu lietot.

2020-10-27 19:24 UTC, alekko commented on static/css/problem.css
> +    margin: 0 auto;
Par daudz atstarpju.

2020-10-28 22:17 UTC, mvanaga commented
Paldies par komentāriem.
Es un Inta kopā veidojām pieslēgšanās skatu un problēmas pieteikumma skatus.
Piektdien ķeramies klāt labojumiem, tad mums noteikti radīsies kādi jautājumi procesā.
Un uzreiz jautājums, ja mēs kopā veidojam divus skatus, tad pietiek, ka viena no mums tikai uztaisa pull request, ja?
Un lai uztaisītu jaunu pull request, man jādara tā pat kā ieprieks darīju:
šim jāspiež Close, un tad jātaisa jauns, ja?

2020-10-29 06:50 UTC, alekko commented
Par pull request - ja strādajat kopā, varat visu taisīt 1 zarā. Un attiecīgi otru zaru/pull request taisīt ciet.Nav jātaisa aktuālais pull request ciet, varat pielikt label - wip(work in progress) un turpināt viena no zariem. Kad pabeigsiet - noņemiet label un uzrakstiet man, ka ir gatavs izskatīšanai.Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: mvanaga <notifications@github.com> Date: 29/10/2020  00:17  (GMT+02:00) To: alekko/fotoaparats <fotoaparats@noreply.github.com> Cc: Aleksandrs Kozlovs <aleksandrs.kozlovs@mail.com>, Comment <comment@noreply.github.com> Subject: Re: [alekko/fotoaparats] Monta (#7) 

Paldies par komentāriem.

Es un Inta kopā veidojām pieslēgšanās skatu un problēmas pieteikumma skatus.

Piektdien ķeramies klāt labojumiem, tad mums noteikti radīsies kādi jautājumi procesā.

Un uzreiz jautājums, ja mēs kopā veidojam divus skatus, tad pietiek, ka viena no mums tikai uztaisa pull request, ja?

Un lai uztaisītu jaunu pull request, man jādara tā pat kā ieprieks darīju:

šim jāspiež Close, un tad jātaisa jauns, ja?



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

2020-10-30 20:07 UTC, mvanaga commented
**- kāds skats tika taisīts**
Login index.html un index.css
**- ekrānšāviņi no uztaisītā skata datora un mobilās versijas**
![fotoapar_dat](https://user-images.githubusercontent.com/70128336/97752163-2b91fa80-1afc-11eb-9b92-f86a54f7a379.JPG)
![fotoapar_mob](https://user-images.githubusercontent.com/70128336/97752078-0a310e80-1afc-11eb-925e-07d1ec52d215.PNG)
**- paraugs no Figma, kā skatam bija jāizskatās**
![fotoapar_figma](https://user-images.githubusercontent.com/70128336/97752055-00a7a680-1afc-11eb-9459-1778ceacd3af.PNG)
**-  ja taisīts pāros, norādīt kas kopā strādāja**
Monta un Inta

2020-11-02 11:14 UTC, mvanaga commented
**- kāds skats tika taisīts**
Problēmas pieteikuma skats problem.html un problem.css
**- ekrānšāviņi no uztaisītā skata datora un mobilās versijas**
![problema_dat](https://user-images.githubusercontent.com/70128336/97861983-48514c80-1d0d-11eb-98ca-fe6806e9190d.JPG)
![problema_mob](https://user-images.githubusercontent.com/70128336/97861997-4be4d380-1d0d-11eb-9df0-45965a3cc502.PNG)
**- paraugs no Figma, kā skatam bija jāizskatās**
![problema_figmaPNG](https://user-images.githubusercontent.com/70128336/97862012-53a47800-1d0d-11eb-978e-86876c0f6600.PNG)
**- ja taisīts pāros, norādīt kas kopā strādāja**
Monta un Inta

2020-11-02 18:29 UTC, alekko commented on login.html
> +    <title>Saimniecisko darbu uzskaites sistēma</title>
Dzēšam ārā šo failu!

2020-11-02 18:29 UTC, alekko commented on index.html
> -  <head>
Nomainām faila nosaukumu uz login.html

2020-11-09 16:30 UTC, alekko requested changes
Daži komentāri, kopumā izskatās ļoti labi.

Salabojiet, lūdzu, tos un liksim iekš main zara!

2020-11-09 16:30 UTC, alekko commented on admin.html
>    <head>
Šo failu var dzēst ārā, neattiecas uz doto pull request.

2020-11-09 16:30 UTC, alekko commented on login.html
> +  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;700&display=swap" rel="stylesheet">
Vai mums vajag abus fontus vai pietiek tikai ar 1?

2020-11-09 16:30 UTC, alekko commented on static/css/login.css
> +.heading1{
Izlabojiet, lūdzu, css failus pēc sekojoša formatējuma:
```css
.klase {
  color: red;
}

.klase {
  color: red;
}

...

2020-11-09 16:30 UTC, alekko commented on static/css/problem.css
> +.user {
Šeit tas pats, kas iepriekšējā komentārā par indentāciju un formatējumu.

2020-11-09 16:30 UTC, alekko commented on static/css/login.css
> +  display: flex;
Dažus no stiliem var panāk ar bootstrap, piemēram, d-flex, m-0-auto, vēl dažus noteikti, ka var. Bet tas nav obligāti.

2020-11-09 16:30 UTC, alekko commented on tasks.html
> +    <title>Saimniecisko darbu uzskaites sistēma</title>
Var dzēst ārā šo failu, jo neattiecas uz šo pull request.

2020-11-09 16:50 UTC, mvanaga commented on static/css/problem.css
> +.user {
Īsti nesaprotam, kur šeit ir problēma, vai atkāpe par lielu? Jo VSCode tādu jau pats liek.

2020-11-09 16:51 UTC, alekko commented on static/css/problem.css
> +.user {
Sakonfigurējiet vscode, lai liek jaunu rindu starp klašu nosaukumiem:
```css
.a1 {
  color: red;
}

.a2 {
  color: red;
}
...

2020-11-16 18:21 UTC, alekko approved these changes

2020-11-16 18:21 UTC, merged