Marianna
alekko/fotoaparats pull request #8
Opened 2020-10-20 16:48 UTC by Rukmane

WIP

2020-10-27 19:28 UTC, alekko requested changes

2020-10-27 19:28 UTC, alekko commented on .vscode/launch.json
> +{
Šo mums noteikti nevajag projektā, dzēšam ārā.

2020-10-27 19:28 UTC, alekko commented on index.html
> +  <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
Kāpēc mums vajag tik daudz fontu?
Varam izmantot 1 fontu visā projektā!

2020-10-27 19:28 UTC, alekko commented on index.html
> +            <div class="ingus">
Klases nosaukumu vajag pamainīt, angliski pirmkārt, otrkārt klasei jāapraksta ko tā dara, lai var kodā saprast aptuveni. Pēc šādas klases grūti kaut ko saprast.

2020-10-27 19:28 UTC, alekko commented on index.html
> +
Vajag šo te?

2020-10-27 19:28 UTC, alekko commented on owner.html
> +  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@500&display=swap" rel="stylesheet">
Tas pats, nevajag tik daudz fontu mums!

2020-10-27 19:28 UTC, alekko commented on owner.html
> +
Lieki enteri.

2020-10-27 19:28 UTC, alekko commented on owner.html
> +
?

2020-10-27 19:28 UTC, alekko commented on owner.html
> +          <tr class="ingus">
Tas pats par klasi.

2020-10-27 19:28 UTC, alekko commented on owner.html
> +
?

2020-10-27 19:28 UTC, alekko commented on owner.html
> +        <table class="table saraksts">
Cenšamies klases angliski rakstīt.

2020-10-27 19:28 UTC, alekko commented on owner.html
> +
?

2020-11-09 16:32 UTC, alekko requested changes
Lūgums izlasīt manus komentārus.

Trūkst ekrānšāviņu, lai labāk skaidrs, kas ticis taisīts un kā izskatās.

Kad izlaboti komentāri un atjaunināts pull request apraksts - dodiet ziņu, iziešu vēlreiz cauri.

2020-11-09 18:04 UTC, Rukmane commented
Liekie enteri un fonti izdzēsti, klases pārrakstītas angliski.
![3](https://user-images.githubusercontent.com/70028596/98579013-bc1fc600-22c6-11eb-9742-264a0962578e.PNG)
![2](https://user-images.githubusercontent.com/70028596/98579014-bcb85c80-22c6-11eb-8af5-62e192230961.PNG)
![1](https://user-images.githubusercontent.com/70028596/98579017-bd50f300-22c6-11eb-9b92-f635c013a703.PNG)

2020-11-16 18:23 UTC, alekko approved these changes

2020-11-16 18:26 UTC, merged